services:
  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Store.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - store-network
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - store-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: redis-server --appendonly yes --requirepass ""

volumes:
  redis-data:
    driver: local

networks:
  store-network:
    driver: bridge