services:
  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Store.API/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"

  store.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

     


   