services:
  store.api:
    image: ${DOCKER_REGISTRY-}storeapi
    build:
      context: .
      dockerfile: Store.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - store.cache
    networks:
      - store-network

  store.cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - store-network
    command: redis-server --appendonly yes

volumes:
  redis-data:

networks:
  store-network:
    driver: bridge