services:
  store.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      # Hot reload support for development
      - .:/src
    develop:
      watch:
        - action: rebuild
          path: ./Store.API
          target: /src/Store.API
        - action: rebuild  
          path: ./Store.Core
          target: /src/Store.Core
        - action: rebuild
          path: ./Store.Service  
          target: /src/Store.Service
        - action: rebuild
          path: ./Store.Repository
          target: /src/Store.Repository

  redis:
    # Override for development - expose Redis CLI for debugging
    ports:
      - "6379:6379"
    # Development specific Redis config
    command: redis-server --appendonly yes --requirepass "" --loglevel debug